jaffle_shop:
  outputs:
    dev:
      catalog: jaffle-shop_dev
      host: dbc-5d563531-a0ca.cloud.databricks.com
      http_path: /sql/1.0/warehouses/07d622b8b0735b42
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
